# Generated by Django 5.1 on 2024-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_django", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
