# Generated by Django 5.2.8 on 2025-11-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django', '0005_aboutpage_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
